@testable import GlucoseSmoothingCore
import XCTest

/// L2 numeric-parity gate: the Swift UKF must match the reference Python `V4UKF`
/// (`backtesting/scripts/2026-07-ukf-smoothing/repeatable/smoothers.py`) — the implementation the
/// Boost benchmark scores against — on captured traces, within a tight tolerance.
///
/// The reference fixture is generated by running `V4UKF().smooth(values, timestamps)` on each trace
/// and recording its `level_offline` (which is exactly `max(smoothedResults, 39)` — the same field
/// the Swift port writes to `.smoothed`). Bit-exact JVM/CPython/Swift parity is NOT claimed (the 9
/// golden vectors are the formal gate); this bounds numeric drift between the two faithful ports.
///
/// The traces deliberately avoid the compression-low regime (all values well above the 75 mg/dL
/// ceiling or never dropping >30 with low IOB), so both filters run with the compression gate off —
/// isolating the shared numeric core (predict/update/sigma/Cholesky/RTS/adaptive-R/segmentation).
final class UkfPythonParityTests: XCTestCase {
    /// Max absolute divergence (mg/dL) permitted between the Swift and Python smoothed level. Two
    /// independent faithful Double ports of identical arithmetic agree far tighter than this; the
    /// margin absorbs incidental floating-point ordering differences without hiding a real port bug.
    private let tolerance = 1e-6

    private struct Trace: Decodable {
        let values: [Double]
        let timestamps: [Int64]
        let level_offline: [Double]
        let rate_online: [Double]
    }

    private func loadReference() throws -> [String: Trace] {
        guard let url = Bundle.module.url(
            forResource: "ukf_python_reference", withExtension: "json", subdirectory: "Fixtures"
        ) else {
            throw XCTSkip("Python reference fixture not bundled")
        }
        return try JSONDecoder().decode([String: Trace].self, from: Data(contentsOf: url))
    }

    func testSwiftMatchesPythonV4UkfSmoothedLevel() throws {
        let reference = try loadReference()
        XCTAssertGreaterThanOrEqual(reference.count, 6, "expected the full reference set")

        var worst = 0.0
        var worstCtx = ""
        var checked = 0

        for (name, trace) in reference.sorted(by: { $0.key < $1.key }) {
            let input = zip(trace.values, trace.timestamps).map {
                InMemoryGlucoseValue(timestamp: $1, value: $0)
            }
            let out = UnscentedKalmanFilter().smooth(input)
            XCTAssertEqual(out.count, trace.level_offline.count, "\(name): length mismatch")

            for i in out.indices {
                let got = out[i].smoothed ?? .nan
                let expected = trace.level_offline[i]
                let err = abs(got - expected)
                checked += 1
                if err > worst { worst = err; worstCtx = "\(name)[\(i)] expected=\(expected) got=\(got)" }
                XCTAssertEqual(
                    got, expected, accuracy: tolerance,
                    "\(name)[\(i)]: Swift smoothed diverged from Python V4UKF level_offline"
                )
            }
        }
        print("UKF Swift↔Python parity: checked \(checked) points, worst |Δ| = \(worst) (\(worstCtx))")
    }
}
